### ISSUE TITLE
Order of skills

### ISSUE THREAD

**Issue by pim-hoeven** [koaning/calmcode-feedback#42] opened 2020-08-04 09:05 UTC
Very cool project! I have been recommending this to people a lot and used it myself as well, thanks!

I think it could be nice to reorder the skills a bit? Even within categories some are more 'I just started working in Python' (e.g. args kwargs, comprehensions) and others are more advanced (gin, FastAPI). I noticed because scikit dummy is before scikit learn.

**Comment by koaning** [comment] 2020-08-04 09:39
Good point. The internal API doesn't allow for ordering yet mainly because we never really had enough content for it to be a problem.

I think the initial grouping still makes sense python/clumper/science/meta. But I could start thinking about the ordering on the inside of it.

**Comment by koaning** [comment] 2020-08-04 09:40
You think `FastAPI` is advanced though? It's just exposing functions to the web. It's not about hosting or anything.

**Comment by pim-hoeven** [comment] 2020-08-04 10:05
Not necessarily advanced no, especially compared to Flask. Maybe FastAPI was not the best example :). Let's say less basic (and probably less used in the first few months of ones career) than comprehensions, readme's and lambda's.

**Comment by koaning** [comment] 2020-08-04 13:56
I don't know if advanced/not advanced is a way I like to split up things. Mainly because there's too many companies I've interacted with in the past that keep referring to linear regression as `advanced analytics`. It's confusing terminology. 

Similar situation: you could say that `GroupedEstimator` is advanced because it is after all a `meta` estimator in scikit-learn. Then again ... it's just `group_by` from a modelling standpoint. 

I might consider other axes though. Some of the tools in python are more like devtools than actual python libraries.

**Comment by pim-hoeven** [comment] 2020-08-04 14:25
Yes, totally agree. I guess it was more a general remark, some things seem to 'naturally' come before others, but there is also a lot of them where it's less clear. Maybe a separate block / page with the most basic things will make the experience calmer for people that are just getting started? 

Anyway, just a suggestion of course. For me personally the current setup works perfectly because I know what I don't know and I really enjoy the content of the new things!

**Comment by koaning** [comment] 2020-08-04 15:13
You're not the first person to mention this acutally. I could make another page that makes it easier for you to find things. Maybe show dependencies in content?

**Comment by koaning** [comment] 2020-09-13 07:49
I have now added a feature that allows me to order the items on the front page.

**Comment by koaning** [comment] 2020-10-01 14:32
I have now also added a tracks page which gives more granular clusters [here](https://calmcode.io/tracks.html). @pim-hoeven is this sufficient for now?

**Comment by koaning** [comment] 2020-11-15 14:02
Closing due to radio silence.

**Closed as completed by koaning** 2020-11-15 14:02 UTC
